### ISSUE TITLE
Sent TX never made it to the blockchain, repost reports Wrong response code: 500

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#141]
Updated server and wallet to version 1.1.0
Attempted to send a tx
Waited a while, tx not seen by recipient
Attempted to repost, Wallet reports:

```
grin@crypto:~$ grin-wallet repost -i 112
Password: 
20190607 21:14:53.686 ERROR grin_wallet_impls::node_clients::http - Post TX Error: Request error: Wrong response code: 500 Internal Server Error with data Body
20190607 21:14:53.687 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
```

Possibly related errors in the grin server logs:
```
20190607 21:09:50.271 INFO grin_chain::chain - Rejected block 00002bc4a32d at 205678: Error { inner:

Old Block }
20190607 21:09:50.274 INFO grin_servers::grin::sync::syncer - synchronized at 587699259326588 @ 205766 [000005f9baec]
20190607 21:11:02.797 INFO grin_chain::chain - Rejected block 000003d4d044 at 205696: Error { inner:

Old Block }
20190607 21:11:02.818 ERROR grin_p2p::protocol - handle_payload: BanReason BanReason { ban_reason: FraudHeight }
20190607 21:11:11.802 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208 with error Not found.
20190607 21:11:23.623 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208 with error Not found.
20190607 21:11:39.614 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208 with error Not found.
20190607 21:11:39.763 INFO grin_api::handlers::pool_api - Pushing transaction e28787e9bd32 to pool (inputs: 1, outputs: 2, kernels: 1)
20190607 21:11:39.806 INFO grin_servers::common::types - DandelionEpoch: relay_peer: new peer chosen: Some(PeerAddr(V4(47.97.163.164:3414)))
20190607 21:11:39.806 INFO grin_servers::common::adapters - Stemming this epoch, relaying to next peer.
20190607 21:14:44.972 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208 with error Not found.
20190607 21:14:53.525 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208 with error Not found.
20190607 21:14:53.678 INFO grin_api::handlers::pool_api - Pushing transaction e28787e9bd32 to pool (inputs: 1, outputs: 2, kernels: 1)
```

Note:  Attempting to repost again appears to have worked.

**Comment by bladedoyle** [comment]
Seems similar to: https://github.com/mimblewimble/grin-wallet/issues/100

**Comment by hashmap** [comment]
@DavidBurkett could it be related to grin++? In that issue we also got `Failure to get output for commitment `

**Comment by DavidBurkett** [comment]
@hashmap Nope. Reposting again would not work if it was the Grin++ issue.

**Comment by hashmap** [comment]
@DavidBurkett I thought the same, but if not “all” strategy was used there is a chance that different subset of outputs was sent second time.

**Comment by DavidBurkett** [comment]
@hashmap Looks like he's just reposting, not generating a new transaction. 
`080d1fe8849ddf5025372833e9f6ba479be6fe2e4200a9e7b5a4ad7c2e5fffd208` suggests it's a different issue. Maybe node wasn't fully synced?

**Comment by bladedoyle** [comment]
Im not using grin++

v1.1.0 server is fully synced with 39 peers

Tried again today to send a tx using grin-wallet v1.1.0

```
grin@crypto:~$ grin-wallet send -m http -d "https://aaaa/bbbb" -s smallest xx
Password: 
Wallet command failed: LibWallet Error: Transaction error
```

No obviosuly related messages in the grin server log.  From that timeframe:
```
20190610 23:27:36.738 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: Some(PeerAddr(V4(46.4.91.48:3414)))
20190610 23:29:05.447 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0984a9d58a468b485325aa98da69c1dabdc2ec06b6f128792cf509037d63d6a326 with error Not found.
20190610 23:29:29.989 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0984a9d58a468b485325aa98da69c1dabdc2ec06b6f128792cf509037d63d6a326 with error Not found.
20190610 23:33:39.092 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0984a9d58a468b485325aa98da69c1dabdc2ec06b6f128792cf509037d63d6a326 with error Not found.
20190610 23:34:14.097 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 0984a9d58a468b485325aa98da69c1dabdc2ec06b6f128792cf509037d63d6a326 with error Not found.
```

I do see it in the grin-wallet txs output.  confirmed=false after a few minutes.  
```
15  Sent Tx      8c1d8912-5f6f-4696-b482-5b926e80c76f  2019-06-11 06:28:46  false       None                 11      1        xx.435630411  xx.436630411  0.001  -xx.001       Yes
```
Calling repost:
```

grin@crypto:~$ grin-wallet repost -i 15
Password: 
20190610 23:34:14.225 ERROR grin_wallet_impls::node_clients::http - Post TX Error: Request error: Wrong response code: 500 Internal Server Error with data Body
20190610 23:34:14.226 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body
```

This time I do see a server log message for the repost:
```
20190610 23:34:14.183 INFO grin_api::handlers::pool_api - Pushing transaction 8a2f87d35668 to pool (inputs: 9, outputs: 2, kernels: 1)
```

several more minutes, grin-wallet txs still shows confirmed=false

Try to repost using wallet v1.0.3:
```
grin@crypto:~$ grin.1.0.3 wallet repost -i 15
Password: 
20190610 23:42:02.632 ERROR grin_util::logger - 
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0': /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2463stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::he9f9d0bd1e2184e1 (0x5590b80ffec7)
             at util/src/logger.rs:240
   1: std::panicking::rust_panic_with_hook::h8cbdfe43764887be (0x5590b8618d19)
             at src/libstd/panicking.rs:495
   2: std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1 (0x5590b86187c1)
             at src/libstd/panicking.rs:398
   3: rust_begin_unwind (0x5590b86186a5)
             at src/libstd/panicking.rs:325
   4: core::panicking::panic_fmt::h4d67173bc68f6d5a (0x5590b863502c)
             at src/libcore/panicking.rs:95
   5: core::panicking::panic_bounds_check::h620ba7e4e283471a (0x5590b8634fe0)
             at src/libcore/panicking.rs:71
   6: <usize as core::slice::SliceIndex<[T]>>::index::h1e1d6f03be3a5144 (0x5590b7281c63)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2463
   7: core::slice::<impl core::ops::index::Index<I> for [T]>::index::h3fb2353e564f4957 (0x5590b7292477)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2331
   8: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h3d35db079e0639e7 (0x5590b725c81a)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/vec.rs:1653
   9: grin_wallet::command::repost::{{closure}}::he83f2ba70de3bd59 (0x5590b6baa640)
             at /home/grin/grin/wallet/src/command.rs:450
  10: grin_wallet::controller::owner_single_use::hf955c5734e2298f6 (0x5590b6bc9788)
             at /home/grin/grin/wallet/src/controller.rs:56
  11: grin_wallet::command::repost::h0575329667a74118 (0x5590b6ba9011)
             at /home/grin/grin/wallet/src/command.rs:448
  12: grin::cmd::wallet_args::wallet_command::hf45109b0f087e851 (0x5590b6bed2fe)
             at src/bin/cmd/wallet_args.rs:612
  13: grin::cmd::wallet::wallet_command::h8f03bf1c199c5fee (0x5590b6b7c895)
             at src/bin/cmd/wallet.rs:53
  14: grin::real_main::hcb7d6f861fe70ad8 (0x5590b6c703ec)
             at src/bin/grin.rs:188
  15: grin::main::h97d4725268dad779 (0x5590b6c6ecc5)
             at src/bin/grin.rs:68
  16: std::rt::lang_start::{{closure}}::h20f473d2e8b37f1e (0x5590b6bb852f)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  17: std::rt::lang_start_internal::{{closure}}::hdfc28107b5be47c9 (0x5590b8618642)
             at src/libstd/rt.rs:59
      std::panicking::try::do_call::h69790245ac2d03fe
             at src/libstd/panicking.rs:310
  18: __rust_maybe_catch_panic (0x5590b862e2e9)
             at src/libpanic_unwind/lib.rs:102
  19: std::panicking::try::h9c1cbc5599e1efbf (0x5590b8619013)
             at src/libstd/panicking.rs:289
      std::panic::catch_unwind::h0562757d03ff60b3
             at src/libstd/panic.rs:398
      std::rt::lang_start_internal::h540c897fe52ba9c5
             at src/libstd/rt.rs:58
  20: std::rt::lang_start::hfcee934b2f948e32 (0x5590b6bb8508)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  21: main (0x5590b6c70b99)
  22: __libc_start_main (0x7f89a6971b96)
  23: _start (0x5590b6aed4f9)
  24: <unknown> (0x0)
```

Ran grin-wallet check.
```
...
20190610 23:50:34.374 WARN grin_wallet_libwallet::internal::restore - Identified 9 wallet_outputs as belonging to this wallet
20190610 23:50:34.376 WARN grin_wallet_controller::command - Wallet check complete
Command 'check' completed successfully
```

Wallet state didnt change.  tx 15 still confirmed=false, all remaining funds "Awaiting Finalization"

I really want to send this tx, so I try repost again:
same errors from the wallet as before,  same message in grin server log:
```
20190610 23:53:00.373 INFO grin_api::handlers::pool_api - Pushing transaction 8a2f87d35668 to pool (inputs: 9, outputs: 2, kernels: 1)
```

To get out of this last time I did a restore from seed....

**Comment by bladedoyle** [comment]
FTR a restore from seed using the v1.1.0 wallet seems to have helped.  After that I am able to send a tx.  (though the wallet lost its transaction history in the process)

**Comment by bladedoyle** [comment]
I updated from 1.0.2 to 1.1.0 with slightly better results.  Here are logs of an attempt to send tx immediately after the update:

```

$ grin-wallet send -d 'http://xxx.yyy:3415' 0.01


Wallet:

20190613 13:49:12.453 INFO grin_wallet - This is Grin Wallet version 1.1.0 (git v1.1.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190613 13:49:16.569 INFO grin_wallet_impls - Using LMDB Backend for wallet
20190613 13:49:17.541 INFO grin_wallet_controller::command - Tx created: 0.010000000 grin to http://xxx.yyy:3415 (strategy 'all')
20190613 13:55:04.073 INFO grin_wallet_controller::command - Tx sent ok


Node:

20190613 13:39:07.249 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190613 13:39:07.249 INFO grin - Using configuration file at /home/ubuntu/.grin/main/grin-server.toml
20190613 13:39:07.249 INFO grin - This is Grin version 1.1.0 (git v1.1.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190613 13:39:07.249 WARN grin::cmd::server - Starting GRIN w/o UI...
20190613 13:39:07.250 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190613 13:39:26.775 INFO grin_servers::grin::server - Starting rest apis at: 127.0.0.1:3413
20190613 13:39:26.775 INFO grin_api::handlers - Starting HTTP API server at 127.0.0.1:3413.
20190613 13:39:26.775 INFO grin_servers::grin::server - Starting dandelion monitor: 127.0.0.1:3413
20190613 13:39:26.776 WARN grin_servers::grin::server - Grin server started.
20190613 13:39:26.785 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: None
20190613 13:43:37.779 INFO grin_servers::common::adapters - Received 13 block headers from 45.77.32.13:3414
20190613 13:43:37.974 INFO grin_servers::common::adapters - Received 13 block headers from 45.77.32.13:3414
20190613 13:43:39.351 INFO grin_servers::grin::sync::syncer - synchronized at 608433037308165 @ 213520 [000000618ddb]
20190613 13:49:19.440 INFO grin_api::handlers::pool_api - Pushing transaction b525d96d7bea to pool (inputs: 1, outputs: 2, kernels: 1)
20190613 13:55:04.031 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: Some(PeerAddr(V4(147.135.11.144:3414)))
20190613 13:55:04.032 ERROR grin_servers::common::adapters - send_tx_request_to_peer: failed: Send("sending on a full channel")
20190613 13:55:04.037 ERROR grin_servers::common::adapters - send_tx_request_to_peer: failed: Send("sending on a full channel")
20190613 13:55:04.068 INFO grin_servers::common::adapters - Stemming this epoch, relaying to next peer.
20190613 13:55:04.069 ERROR grin_servers::common::adapters - send_tx_request_to_peer: failed: Send("sending on a full channel")
20190613 13:55:13.008 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 608433037308165, peer_difficulty 608455969307358, threshold 11375321585 (last 5 blocks), enabling sync
20190613 13:58:44.057 INFO grin_servers::grin::dandelion_monitor - dand_mon: embargo expired for b525d96d7bea, fluffed successfully.
20190613 13:59:06.963 INFO grin_servers::grin::sync::header_sync - sync: ban a fraud peer: 45.77.150.172:3414, claimed height: 213537, total difficulty: 608472181399907
20190613 13:59:06.973 INFO grin_servers::grin::sync::syncer - synchronized at 608433037308165 @ 213520 [000000618ddb]
20190613 13:59:24.998 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 608433037308165, peer_difficulty 608476864366189, threshold 11375321585 (last 5 blocks), enabling sync
20190613 14:03:19.014 INFO grin_servers::grin::sync::header_sync - sync: ban a fraud peer: 34.74.219.251:3414, claimed height: 213546, total difficulty: 608493418021610
20190613 14:03:19.024 INFO grin_servers::grin::sync::syncer - synchronized at 608433037308165 @ 213520 [000000618ddb]
20190613 14:03:57.898 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09ccfa7e8b952e4af0b456ac22be4b366d82e2d5232b63fca0be9138b7fa449953 with error Not found.
20190613 14:05:14.086 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: false (90%), relay: Some(PeerAddr(V4(94.130.207.236:3414)))
20190613 14:07:04.323 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 608433037308165, peer_difficulty 608505355927438, threshold 11375321585 (last 5 blocks), enabling sync
20190613 14:10:35.381 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09ccfa7e8b952e4af0b456ac22be4b366d82e2d5232b63fca0be9138b7fa449953 with error Not found.
20190613 14:10:35.389 INFO grin_servers::grin::sync::syncer - synchronized at 608433037308165 @ 213520 [000000618ddb]
20190613 14:15:05.748 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 608433037308165, peer_difficulty 608522191305116, threshold 11375321585 (last 5 blocks), enabling sync
20190613 14:15:24.129 INFO grin_servers::common::types - DandelionEpoch: next_epoch: is_stem: true (90%), relay: Some(PeerAddr(V4(88.198.15.74:3414)))




$ time grin-wallet -p xxx txs
...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 175  Sent Tx      eb0a3255-e9ec-48cc-882b-14273845b4b7  2019-06-13 13:49:18  false       None                 1       1        0.0464382      0.0644382      0.008  -0.018        Yes
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Command 'txs' completed successfully

real    1m49.107s
user    0m0.910s
sys     0m0.016s


Later:

$ rin-wallet -p xxx txs
...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 175  Sent Tx      eb0a3255-e9ec-48cc-882b-14273845b4b7  2019-06-13 13:49:18  true        2019-06-13 14:51:07  1       1        0.0464382      0.0644382      0.008  -0.018        Yes
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

So this time the tx did post - eventually (after about 45 minutes)
Its not clear why running 'grin wallet txs' takes almost 2 minutes.

**Comment by bladedoyle** [comment]
I see now why the wallet hangs for a long time.   It is becaues the grin server cant keep the chain in sync, and its entering "sync" mode often to try to cach up

20190614 13:31:01.663 INFO grin_servers::grin::sync::syncer - sync: total_difficulty 16883965720, peer_difficulty 16883974905, threshold 7758 (last 5 blocks), enabling sync

While the server is in sync mode, the wallet waits so it can do a refresh.

So, this isnt a wallet problem, its a p2p problem

**Comment by quentinlesceller** [comment]
Closing for #153. This is the same issue. Failure to get output for commitment.
