### ISSUE TITLE
'grin.wallet -e listen' thread 'apis' panicked at 'error binding error creating server listener: (address already in use)

### ISSUE THREAD

**Issue by BLOCKCHAINSMOKER** [mimblewimble/grin-wallet#302]
I don't know if there is a better place to ask this question but I usually shut down 'grin.wallet -e listen' by cntrl z. However sometimes if I do this and then try to restart the  -e listener it gives me the following error. This is not such an issue if I am physically in front of the computer because I can close the terminal and then restart -e listener. However if I am accessing the wallet via ssh this becomes and issue for me. Perhaps there is an easy code to use but it is not readily available for unsophisticated users and is not provided in the grin.wallet user guide. 

20200118 23:55:15.161 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0$
20200118 23:55:15.161 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20200118 23:55:15.289 ERROR grin_util::logger -
thread 'apis' panicked at 'error binding to 0.0.0.0:3415: error creating server listener: Address already in use (os$
   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
   3: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
   4: hyper::server::Server<hyper::server::tcp::AddrIncoming,()>::bind
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  11: start_thread
  12: __clone

Is there a better way to close the grin.wallet? Is there something I can do when this happens?

**Comment by BLOCKCHAINSMOKER** [comment]
I think it is because I used control z instead of control c to close wallet. I will close this issue unless I run into the problem again.
