### ISSUE TITLE
crash wallet init_send_tx

### ISSUE THREAD

**Issue by oneevil** [mimblewimble/grin-wallet#361]
init_send_tx

```
20200309 11:47:36.843 ERROR grin_util::logger -
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 19)': src/libcore/result.rs:1188   0: grin_util::logger::send_panic_$
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   4: core::result::unwrap_failed
             at src/libcore/result.rs:1188
   5: <grin_wallet_impls::adapters::http::HttpSlateSender as grin_wallet_impls::adapters::SlateSender>::send_tx
   6: grin_wallet_api::owner::Owner<L,C,K>::init_send_tx
   7: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::init_send_tx
   8: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
   9: easy_jsonrpc_mw::handle_call
  10: easy_jsonrpc_mw::handle_parsed_request
  11: easy_jsonrpc_mw::Handler::handle_request
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll
  13: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  15: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  16: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  17: tokio::task::core::Core<T>::poll
  18: std::panicking::try::do_call
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: tokio::task::harness::Harness<T,S>::poll
  21: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  22: tokio::runtime::thread_pool::worker::GenerationGuard::run
  23: std::thread::local::LocalKey<T>::with
  24: tokio::runtime::thread_pool::worker::Worker::run
  25: tokio::task::core::Core<T>::poll
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  28: tokio::task::harness::Harness<T,S>::poll
  29: tokio::runtime::context::enter
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: std::panicking::try::do_call
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
  35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  36: start_thread
  37: __clone
```

**Comment by yeastplume** [comment]
Could you confirm whether this is still happening on 4.0.0?

**Comment by oneevil** [comment]
4.0.0

**Comment by wiesche89** [comment]
Tested again with the current testnet wallet. Failed responses are handled without a panic and fall back to Slatepack. This was fixed in PR #750
