### ISSUE TITLE
Thread 'unnamed' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }'

### ISSUE THREAD

**Issue by madmarks** [mimblewimble/grin-wallet#365]
I am trying to run `grin-wallet info` and I get this error:

> $ grin-wallet info
> 20200312 16:45:27.219 ERROR grin_util::logger - 
> thread 'unnamed' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }': src/libcore/result.rs:1188
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: grin_util::logger::send_panic_to_log::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>    4: rust_begin_unwind
>    5: core::panicking::panic_fmt
>    6: core::result::unwrap_failed
>    7: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
>    8: <std::future::GenFuture<T> as core::future::future::Future>::poll
>    9: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
>   10: tokio::runtime::context::enter
>   11: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
>   12: std::sys_common::backtrace::__rust_begin_short_backtrace
>   13: __rust_maybe_catch_panic
>   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>   16: std::sys::unix::thread::Thread::new::thread_start
>   17: _pthread_start
> 
>
> Thread 'unnamed' panicked with message:
> "cannot access native cert store: Custom { kind: InvalidData, error: BadDER }"
> See /Users/xxx/.grin/main/grin-wallet.log for further details.
> 20200312 16:45:27.222 ERROR grin_util::logger - 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any': src/libcore/result.rs:1188
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: grin_util::logger::send_panic_to_log::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>    4: rust_begin_unwind
>    5: core::panicking::panic_fmt
>    6: core::result::unwrap_failed
>    7: std::panicking::try::do_call
>    8: __rust_maybe_catch_panic
>    9: crossbeam_utils::thread::scope
>   10: grin_wallet_impls::client_utils::client::Client::post
>   11: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_version_info
>   12: grin_wallet::cmd::wallet::wallet_command
>   13: grin_wallet::real_main
>   14: grin_wallet::main
>   15: std::rt::lang_start::{{closure}}
>   16: std::panicking::try::do_call
>   17: __rust_maybe_catch_panic
>   18: std::rt::lang_start_internal
>   19: main
> 
> Thread 'main' panicked with message:
> "called `Result::unwrap()` on an `Err` value: Any"
> See /Users/xxx/.grin/main/grin-wallet.log for further details.

macOS Catalina 10.15.3
grin-wallet 3.1.1 built from source

**Comment by marekyggdrasil** [comment]
Reproduced, same problem here. Wallet `grin-wallet 3.1.1`, node `2.0.0 (Proto: 1)`

**Comment by marekyggdrasil** [comment]
I downgraded and it seems to have resolved this particular problem for me. The most recent version of the wallet that works for me is `3.1.0-beta.1`, I also updated my node to most recent currently available `3.0.0-alpha.1` to exclude possibility of the problem being caused by the node.

**Comment by mably** [comment]
Same pb here when running latest grin-wallet master on Windows using a binary built under WSL.

**Comment by marekyggdrasil** [comment]
Reproduced again with

```
$ ./grin-wallet help
grin-wallet 4.0.0
```

**Comment by wiesche89** [comment]
The old certificate store panic path is no longer present. The current TLS client introduced in #779 returns errors instead of crashing.
