### ISSUE TITLE
Thread Panic: byte index out of bounds

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-wallet#467]
Unsure what is happening here. Happens during the building of a change output.
```
20200710 13:55:55.626 DEBUG grin_wallet_libwallet::internal::selection - Building change outputs: total change: 26836592165 (1 outputs)
20200710 13:55:55.638 DEBUG grin_core::libtx::build - Building output: 26836592165, Commitment(099d5ebbf14de2cd204264281e94ba196683d4888123428f78269ca5f49a8bcb66)
20200710 13:55:55.697 ERROR grin_util::logger -
thread 'tokio-runtime-worker' panicked at 'byte index 2 is out of bounds of ``': /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/str/mod.rs:1987   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
   4: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
   5: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::{{closure}}
   6: grin_util::hex::from_hex
   7: <grin_wallet_util::ov3::OnionV3Address as core::convert::TryFrom<&str>>::try_from
   8: grin_wallet_impls::tor::config::is_tor_address
   9: grin_wallet_impls::tor::config::complete_tor_address
  10: grin_wallet_impls::adapters::create_sender
  11: grin_wallet_api::owner::Owner<L,C,K>::init_send_tx
  12: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc_s::OwnerRpcS>::init_send_tx
  13: <dyn grin_wallet_api::owner_rpc_s::OwnerRpcS as easy_jsonrpc_mw::Handler>::handle
  14: easy_jsonrpc_mw::handle_call
  15: easy_jsonrpc_mw::handle_parsed_request
  16: easy_jsonrpc_mw::Handler::handle_request
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  19: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  20: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  21: tokio::task::core::Core<T>::poll
  22: tokio::task::harness::Harness<T,S>::poll
  23: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  24: tokio::runtime::thread_pool::worker::GenerationGuard::run
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::thread_pool::worker::Worker::run
  27: tokio::task::core::Core<T>::poll
  28: tokio::task::harness::Harness<T,S>::poll
  29: tokio::runtime::blocking::pool::Inner::run
  30: tokio::runtime::context::enter
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:87
  34: start_thread
  35: clone
```

**Comment by yeastplume** [comment]
Doesn't look like this was building the output per-se, but failed when trying to parse a tor address from a given string. What was the exact call and parameters here?

**Comment by ardocrat** [comment]
Seems like old issue, function `complete_tor_address` is not using anymore + there are checks before unwrap results everywhere.
