### ISSUE TITLE
Need error handling around slatepack parsing

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#468]
grin-wallet panics on invalid slatepack data

```
grinfloo@crypto:~$ grin-wallet --floonet unpack
Password: 
Please paste your encoded slatepack message:
BEGINSLATEPACK. xxx
20200711 11:24:49.139 ERROR grin_util::logger - 
thread 'main' panicked at 'slice index starts at 20 but ends at 19': libwallet/src/slatepack/armor.rs:73   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/panicking.rs:111
   4: core::slice::slice_index_order_fail
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/slice/mod.rs:2758
   5: grin_wallet_libwallet::slatepack::armor::SlatepackArmor::decode
   6: grin_wallet::cmd::wallet_args::prompt_slatepack
   7: grin_wallet::cmd::wallet_args::parse_unpack_args
   8: grin_wallet::cmd::wallet_args::parse_and_execute
   9: grin_wallet::cmd::wallet_args::wallet_command
  10: grin_wallet::cmd::wallet::wallet_command
  11: grin_wallet::real_main
  12: grin_wallet::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
      std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:51
  15: main
  16: __libc_start_main
  17: _start



Thread 'main' panicked with message:
"slice index starts at 20 but ends at 19"
See /home/grinfloo/.grin/floo/grin-wallet.log for further details.
```

**Comment by wiesche89** [comment]
This was fixed in #764. Invalid Slatepack input now returns an error instead of panicking.
