### ISSUE TITLE
process_invoice_tx invok error

### ISSUE THREAD

**Issue by yangchunhe** [mimblewimble/grin-wallet#487]
20200721 16:44:02.626 ERROR grin_util::logger -
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': /home/vsts/work/1/s/api/src/owner.rs:853   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/xxx/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/xxx/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/xxx/src/libcore/panicking.rs:111
   4: core::panicking::panic
             at /rustc/xxx/src/libcore/panicking.rs:54
   5: grin_wallet_api::owner::Owner<L,C,K>::process_invoice_tx
   6: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::process_invoice_tx
   7: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
   8: easy_jsonrpc_mw::handle_call
   9: easy_jsonrpc_mw::handle_parsed_request
  10: easy_jsonrpc_mw::Handler::handle_request
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  13: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  14: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  15: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: tokio::runtime::context::enter
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/xxx/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/xxx/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/xxx/src/libstd/sys/unix/thread.rs:87
  30: start_thread
  31: __clone

**Comment by wiesche89** [comment]
This was fixed in #763. process_invoice_tx no longer unwraps an optional result, and send failures are handled without panicking. Closing as resolved.
