### ISSUE TITLE
Thread panic: 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any'

### ISSUE THREAD

**Issue by jyap808** [mimblewimble/grin-wallet#496]
```
20200728 22:46:11.486 ERROR grin_util::logger -
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any': impls/src/client_utils/client.rs:336   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:490
   2: rust_begin_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:388
   3: core::panicking::panic_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/panicking.rs:101
   4: core::option::expect_none_failed
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/option.rs:1272
   5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   6: crossbeam_utils::thread::scope
   7: grin_wallet_impls::client_utils::client::Client::post
   8: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_chain_tip
   9: grin_wallet_libwallet::api_impl::owner::update_outputs
  10: grin_wallet_libwallet::api_impl::owner::update_wallet_state
  11: grin_wallet_libwallet::api_impl::owner::retrieve_summary_info
  12: grin_wallet_api::owner::Owner<L,C,K>::retrieve_summary_info
  13: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::retrieve_summary_info
  14: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
  15: easy_jsonrpc_mw::handle_call
  16: easy_jsonrpc_mw::handle_parsed_request
  17: easy_jsonrpc_mw::Handler::handle_request
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  21: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  22: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::thread_pool::worker::Context::run_task
  27: tokio::runtime::thread_pool::worker::Context::run
  28: tokio::macros::scoped_tls::ScopedKey<T>::set
  29: tokio::runtime::thread_pool::worker::run
  30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: tokio::runtime::task::harness::Harness<T,S>::poll
  33: tokio::runtime::blocking::pool::Inner::run
  34: tokio::runtime::context::enter
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/sys/unix/thread.rs:87
  38: start_thread
  39: __clone
```

**Comment by yeastplume** [comment]
This looks like a communication issue with the node, but there's nothing here I'll be able to produce. Could you please follow the steps below to provide as much information as possible to help us look into this (log files and a description of what's happening at the time would be useful)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Run '...'
2. Expect '....'
3. Scroll down to '....'
4. See error

**Relevant Information**
An excerpt from the logs or a detailed error message.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 1.0.1]

**Additional context**
Add any other context about the problem here.

**Comment by devilrayzl** [comment]
@jyap808  Have you solve this problem?
The error happens on my node.
```
20210121 06:46:34.054 DEBUG grin_store::lmdb - DB Mapsize for /root/.grin/main/wallet_data/db/lmdb is 549755813888
20210121 06:46:34.056 DEBUG grin_wallet_impls::lifecycle::seed - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed
20210121 06:46:36.005 DEBUG grin_wallet_libwallet::api_impl::owner_updater - Updating outputs from node
20210121 06:46:36.006 ERROR grin_util::logger - 
thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': impls/src/client_utils/client.rs:349   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  10: start_thread
  11: __clone

```

```
20210121 06:46:36.007 ERROR grin_util::logger - 
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any': impls/src/client_utils/client.rs:351   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   7: grin_wallet_impls::client_utils::client::Client::send_request
   8: grin_wallet_impls::client_utils::client::Client::post
   9: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_chain_tip
  10: grin_wallet_libwallet::internal::updater::refresh_outputs
  11: grin_wallet_libwallet::api_impl::owner::update_outputs
  12: grin_wallet_libwallet::api_impl::owner::update_wallet_state
  13: grin_wallet_libwallet::api_impl::owner::retrieve_summary_info
  14: grin_wallet_api::owner::Owner<L,C,K>::retrieve_summary_info
  15: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::retrieve_summary_info
  16: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
  17: easy_jsonrpc_mw::handle_call
  18: easy_jsonrpc_mw::handle_parsed_request
  19: easy_jsonrpc_mw::Handler::handle_request
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  22: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  23: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  24: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  26: tokio::runtime::task::raw::poll
  27: std::thread::local::LocalKey<T>::with
  28: tokio::runtime::thread_pool::worker::Context::run_task
  29: tokio::runtime::thread_pool::worker::Context::run
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
  31: tokio::runtime::thread_pool::worker::run
  32: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  33: tokio::runtime::task::core::Core<T,S>::poll
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: tokio::runtime::task::harness::Harness<T,S>::poll
  36: tokio::runtime::blocking::pool::Inner::run
  37: tokio::runtime::context::enter
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  41: start_thread
  42: __clone
```

It panicked when I invoke `retrieveSummaryInfo` or `getRetrieveTxsByTxId`.

**Comment by wiesche89** [comment]
This was fixed by later changes to the Tokio runtime handling. Node connection failures now return an error instead of causing this panic, so i’m closing this as resolved!
