### ISSUE TITLE
The Trust Settings Record was corrupted

### ISSUE THREAD

**Issue by marekyggdrasil** [mimblewimble/grin-wallet#554]
**Describe the bug**
Wallet crashes with "The Trust Settings Record was corrupted" error message on macOS Catalina 10.15.7

**To Reproduce**
1. Download source or binary of the wallet of any version after `3.1.0-beta.1`
2. Run `info` command

**Stack trace**

```
$ ./grin-wallet info
20201218 17:57:13.871 ERROR grin_util::logger - 
thread 'main' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }': /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:46   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::thread_pool::ThreadPool::block_on
  13: tokio::runtime::context::enter
  14: grin_wallet_impls::client_utils::client::Client::send_request
  15: grin_wallet_impls::client_utils::client::Client::post
  16: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_version_info
  17: grin_wallet::cmd::wallet::wallet_command
  18: grin_wallet::real_main
  19: grin_wallet::main
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: std::rt::lang_start::{{closure}}
  22: std::rt::lang_start_internal
  23: _main



Thread 'main' panicked with message:
"cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }"
See /Users/marek/.grin/main/grin-wallet.log for further details.
```

**Expected behavior**
Expected to obtain the `info` command output.

**Desktop (please complete the following information):**
 - OS: `macOS Catalina`
 - Version: `10.15.7`

**Additional context**

Seems related https://github.com/mimblewimble/grin-wallet/issues/365

**Comment by marekyggdrasil** [comment]
Seem related https://github.com/mimblewimble/grin-wallet/issues/365

**Comment by marekyggdrasil** [comment]
More related issues, https://github.com/ctz/rustls-native-certs/issues/4 has it working with `sudo` (I'm not going to try it), but it makes me suspect that maybe its a matter of adding the user to some system group that has access to the certificates.

**Comment by marekyggdrasil** [comment]
Persists in the most recent release `v5.0.2`

```
$ ./grin-wallet -V
grin-wallet 5.0.2
$ ./grin-wallet info
20210112 21:09:19.073 ERROR grin_util::logger - 
thread 'main' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }': /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:46   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::enter::Enter::block_on
  13: tokio::runtime::thread_pool::ThreadPool::block_on
  14: tokio::runtime::context::enter
  15: grin_wallet_impls::client_utils::client::Client::send_request
  16: grin_wallet_impls::client_utils::client::Client::post
  17: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_version_info
  18: grin_wallet::cmd::wallet::wallet_command
  19: grin_wallet::real_main
  20: grin_wallet::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: _main



Thread 'main' panicked with message:
"cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }"
See /Users/marek/.grin/main/grin-wallet.log for further details.
```

**Comment by quentinlesceller** [comment]
This is a weird error. I've been using Grin on macOS since its inception and it never happened to me. Do you have a special config related to certificates maybe?

**Comment by jaspervdm** [comment]
As far as I can see this it not an issue with Grin itself, but rather with your OS. A quick google search gives me this result: https://apple.stackexchange.com/questions/374890/how-to-remove-a-corrupted-trust-settings-record

**Comment by marekyggdrasil** [comment]
I also performed exactly the same quick google search and found same link before I opened this issue, I just fail to see how this result is any helpful. I develop Python, JavaScript and Ruby on my Mac, the only thing that has issues with certificates is grin-wallet.

**Comment by marekyggdrasil** [comment]
Yes but why?! Literally everything else works, I all the package managers are able to use the system certificates (pip, npm, bundler, brew...) but the only single piece of software that does not work is the grin-wallet...

I will try to build it from source, maybe the compiler will use the correct certificate. Will write here if it helped.

**Comment by marekyggdrasil** [comment]
Nope
```
$ cd target/release/
$ ./grin-wallet -V
grin-wallet 5.0.2
$ ./grin-wallet -r https://grinnode.live:3413 info
20210114 18:50:55.367 ERROR grin_util::logger - 
thread 'main' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }': /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:46   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::enter::Enter::block_on
  13: tokio::runtime::thread_pool::ThreadPool::block_on
  14: tokio::runtime::context::enter
  15: grin_wallet_impls::client_utils::client::Client::send_request
  16: grin_wallet_impls::client_utils::client::Client::post
  17: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_version_info
  18: grin_wallet::cmd::wallet::wallet_command
  19: grin_wallet::real_main
  20: grin_wallet::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: _main



Thread 'main' panicked with message:
"cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }"
See /Users/marek/.grin/main/grin-wallet.log for further details.
```

**Comment by marekyggdrasil** [comment]
I believe this https://github.com/ctz/rustls-native-certs/issues/4#issuecomment-593443164 code snippet can detect which certificate in the keychain breaks rust, but I can't run it because author did not provide Cargo.toml

**Comment by marekyggdrasil** [comment]
ok I managed to make his code snippet work, I run

```
cargo new cert_test
```

to create new rust project, then I add the dependencies to `Cargo.toml`

```toml
[dependencies]
rustls = "0.19.0"
rustls-native-certs = "0.5.0"
security-framework = "2.0.0"
```

and run it

```
$ cargo run
    Updating crates.io index
  Downloaded security-framework-sys v2.0.0
  Downloaded core-foundation v0.9.1
  Downloaded core-foundation-sys v0.8.2
  Downloaded security-framework v2.0.0
  Downloaded rustls-native-certs v0.5.0
  Downloaded libc v0.2.82
  Downloaded 6 crates (642.9 KB) in 2.76s
   Compiling core-foundation-sys v0.8.2
   Compiling libc v0.2.82
   Compiling bitflags v1.2.1
   Compiling security-framework-sys v2.0.0
   Compiling core-foundation v0.9.1
   Compiling security-framework v2.0.0
   Compiling rustls-native-certs v0.5.0
   Compiling cert_test v0.1.0 (/Users/marek/Development/cert-test/cert_test)
warning: unused import: `rustls_native_certs::load_native_certs`
 --> src/main.rs:2:5
  |
2 | use rustls_native_certs::load_native_certs;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `security_framework::os::macos::certificate::SecCertificateExt`
 --> src/main.rs:3:5
  |
3 | use security_framework::os::macos::certificate::SecCertificateExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 14.35s
     Running `target/debug/cert_test`
certs.len():3
(SecCertificate { subject: "rad.nyu.edu" }, Ok(()))
(SecCertificate { subject: "rad.nyu.edu" }, Ok(()))
(SecCertificate { subject: "rad.nyu.edu" }, Ok(()))
```

does find three certificates but none of them are causing the error, they are all `Ok(())`, will dig in more...

**Comment by marekyggdrasil** [comment]
Anyway... I will close this, the problem is with `rustls-native-certs` module so I asked them for help. Of course when resolved I will shot a comment here.

**Comment by jaspervdm** [comment]
Thanks!

**Comment by trevyn** [comment]
I hit this too. Fixed it by doing (in the Terminal):

```
/usr/bin/security dump-trust-settings -d
```

Which reported the names of two certs with this error. Went into the Keychain Access app, manually deleted them, and now it works. :)

**Comment by marekyggdrasil** [comment]
4.0.0

```
$ grin-wallet -V
grin-wallet 4.0.0
```
run
```
$ grin-wallet init -h
20221122 07:18:16.027 ERROR grin_util::logger - 
thread 'unnamed' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }': /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:46   0: backtrace::backtrace::trace
```
now 5.1.0
```
$ grin-wallet -V
grin-wallet 5.1.0
```
run
```
$ grin-wallet init -h
20221122 07:23:32.594 ERROR grin_wallet_impls::node_clients::http - Error calling get_version: Request error: Cannot make request: error sending request for url (http://127.0.0.1:3413/v2/foreign): error trying to connect: tcp connect error: Connection refused (os error 61)
20221122 07:23:32.595 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Client Callback Error: Error calling get_version: Request error: Cannot make request: error sending request for url (http://127.0.0.1:3413/v2/foreign): error trying to connect: tcp connect error: Connection refused (os error 61)
Please enter a password for your new wallet
Password: 
Confirm Password: 
20221122 07:23:36.493 WARN grin_wallet_impls::lifecycle::seed - Generating wallet seed file at: /Users/marek/Development/open-source/grinventions/wallets/tst/wallet_data/wallet.seed
Your recovery phrase is:

champion worry lucky soon zoo capable section spatial robust card figure surge situate mountain that team mammal chapter egg tide border panther change army

Please back-up these words in a non-digital format.
Command 'init' completed successfully
```
so it was resolved!
